### ISSUE TITLE
Implement Find Command

### ISSUE THREAD

**Issue by Ben-Hanan** [AY2021S1-CS2103T-W13-1/tp#134]
`find alex` will work in the same way view does. If you are on the applicant list panel, it will search in applicants, if you are in staff list panel it will search in staffs.

`find -applicant alex` will work anywhere in the app and bring you to the applicant list view with the filtered list.
same for `find -staff alex`

**Comment by Hou-Rui** [comment]
I have enforced that `find` must be used with `-applicant` or `-staff`, otherwise there will be infinite troubles in the tests. I actually think we better make commands context-free, which means that the operations executed should not be related to the context of the command.
